name: Build and Publish Library

on:
  push:
    tags:
      - "v*"
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          cd src
          npm install

      - name: Build library
        run: |
          cd src
          npm run build

      - name: Publish to npm
        run: |
          cd src
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
